### ISSUE TITLE
-bash: syntax error near unexpected token `then'

### ISSUE THREAD

**Issue by jasonkarns** [rkh/rbenv-update#27]
error after merging #26 (reverted for now)

```
[snip]
+ command=sh-update
+ case "$command" in
++ command -v rbenv-sh-update
+ command_path=/usr/local/var/rbenv/plugins/rbenv-update/bin/rbenv-sh-update
+ '[' -z /usr/local/var/rbenv/plugins/rbenv-update/bin/rbenv-sh-update ']'
+ shift 1
+ exec /usr/local/var/rbenv/plugins/rbenv-update/bin/rbenv-sh-update
++ basename /usr/local/bin/bash
+ shell=bash
+ case "$shell" in
+ cat
-bash: syntax error near unexpected token `then'
```

**Comment by jasonkarns** [comment]
Getting this error on OS X, GNU bash, version 4.3.42(1)-release.

@mislav anything jump out at you?

**Comment by mislav** [comment]
Oops, rbenv bug with multiline eval. Before, the output of `sh-update` was a single-line script.

Now fixed in https://github.com/sstephenson/rbenv/commit/0f44c57d0868885fd20e11348f73b575035696ee. However, people who install this plugin with an old version of rbenv will get the cryptic error if you merge my PR back in.

**Comment by mislav** [comment]
Workaround in 362b570cc8f26d03fd51bd2a7b51dd901bfa1844

**Comment by jasonkarns** [comment]
Thanks. Revert reverted (707c8d26c9c259c656a4908eca3cd47538d80d8d) and fix merged in 4d340a6d3a1c2e23dc40733da9d753c2e767fbab

**Comment by mislav** [comment]
Sorry for not testing whis with bash, and thanks for your patience!

**Comment by jasonkarns** [comment]
No worries. Thanks for all the work on rbenv proper!​
